### ISSUE TITLE
Performance optimizations [meta]

### ISSUE THREAD

**Issue by abensonca** [galacticusorg/galacticus#107]
```[tasklist]
### Tasks
- [x] #108 Optimize integration of surface density of star formation rate
- [x] #109 Optimize adiabatically-contracted halo potential functions
- [x] #130 Event hook code is inefficient
```
