### ISSUE TITLE
Dark matter physics modeling improvements [meta]

### ISSUE THREAD

**Issue by abensonca** [galacticusorg/galacticus#96]
- [ ] #97 Add a satellite virial orbit class that takes into account actual halo mass
- [ ] #98 Implement the updated "MAC" model of adiabatic contraction
- [ ] #99 Triaxial halos for satellite orbit calculations
- [ ] #100 Outer profile for dark matter halos
- [x] #101 Dynamical friction in cored profiles
- [ ] #102 Model for cores in dark matter profiles due to bursty star formation
- [ ] #106 Zhang, Ma, Riotto model for environmental effects on halo merger rates

**Comment by abensonca** [comment]
Obsoleted by use of a Project to track this work.
